apiVersion: v1
kind: Service
metadata:
  name: clonecloud-frontend-service
  namespace: {{ .Values.global.namespace | default "clonecloud-main" }}
  labels:
    app: clonecloud
    component: frontend
spec:
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      {{- if eq .Values.frontend.serviceType "NodePort" }}
      nodePort: {{ .Values.frontend.nodePort }}
      {{- end }}
      name: http
  selector:
    app: clonecloud
    component: frontend
  type: {{ .Values.frontend.serviceType | default "NodePort" }}
